[package]
name = "reflow"
version = "0.1.0"
authors = ["ko1N <ko1N1337@gmail.com>"]
edition = "2018"

[dependencies]
memflow = { version = "0.1", features = ["inventory"] }
memflow-win32 = "0.1"
unicorn = "0.9"
log = { version = "0.4", default-features = false }
